// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiraddnOmZkZsXezxro6Km19qv2Cu3cQ8',
    appId: '1:1015223075340:web:bb451c1ed45f0357d3a429',
    messagingSenderId: '1015223075340',
    projectId: 'chatapp-c5cab',
    authDomain: 'chatapp-c5cab.firebaseapp.com',
    storageBucket: 'chatapp-c5cab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZQaFW7xfNrHMCeiOD8RBwf5e6lsqoX7o',
    appId: '1:1015223075340:android:a85e546b441f6921d3a429',
    messagingSenderId: '1015223075340',
    projectId: 'chatapp-c5cab',
    storageBucket: 'chatapp-c5cab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgO3LnPU8xzX7EhzT7otg0KrMP-caYTes',
    appId: '1:1015223075340:ios:6d787e733dd27c99d3a429',
    messagingSenderId: '1015223075340',
    projectId: 'chatapp-c5cab',
    storageBucket: 'chatapp-c5cab.appspot.com',
    iosClientId:
        '1015223075340-uubp1mqcu2n4pd398vpmhdrar79qftcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgO3LnPU8xzX7EhzT7otg0KrMP-caYTes',
    appId: '1:1015223075340:ios:f27fffc5e3ae7243d3a429',
    messagingSenderId: '1015223075340',
    projectId: 'chatapp-c5cab',
    storageBucket: 'chatapp-c5cab.appspot.com',
    iosClientId:
        '1015223075340-mp47f1ejgbfiv3tvcpfgs418957jq6ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipApp.RunnerTests',
  );
}
